# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KaiKlicker_1.0.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import time
import threading
from pynput.mouse import Button, Controller
from pynput.keyboard import Listener, KeyCode

delay = 0.001
button = Button.left
start_stop_key = KeyCode(char='[')
exit_key = KeyCode(char=']')


class ClickMouse(threading.Thread):
    def __init__(self, delay, button):
        super(ClickMouse, self).__init__()
        self.delay = delay
        self.button = button
        self.running = False
        self.program_running = True

    def start_clicking(self):
        self.running = True

    def stop_clicking(self):
        self.running = False

    def exit(self):
        self.stop_clicking()
        self.program_running = False


on = False


# if on:

def run(self):
    while self.program_running:
        while self.running:
            mouse.click(self.button)
            time.sleep(self.delay)
        time.sleep(0.1)


#    def run(self):
#        while self.program_running:
#            while self.running:
#                mouse.click(self.button)
#                time.sleep(self.delay)
#            time.sleep(0.1)

# else:
#    pass

mouse = Controller()
click_thread = ClickMouse(delay, button)
click_thread.start()


def on_press(key):
    if key == start_stop_key:
        if click_thread.running:
            click_thread.stop_clicking()
        else:
            click_thread.start_clicking()
    elif key == exit_key:
        click_thread.exit()
        listener.stop()


with Listener(on_press=on_press) as listener:
    listener


def start(self):
    on = True
    run()
    print("worked")


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(208, 191)
        icon = QtGui.QIcon.fromTheme("mouse")
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Intro_TXT = QtWidgets.QLabel(self.centralwidget)
        self.Intro_TXT.setGeometry(QtCore.QRect(20, 20, 251, 21))
        self.Intro_TXT.setObjectName("Intro_TXT")
        self.ClicksPerSec_VAR = QtWidgets.QSpinBox(self.centralwidget)
        self.ClicksPerSec_VAR.setGeometry(QtCore.QRect(111, 50, 81, 22))
        self.ClicksPerSec_VAR.setMinimum(1)
        self.ClicksPerSec_VAR.setMaximum(1000000000)
        self.ClicksPerSec_VAR.setObjectName("ClicksPerSec_VAR")
        self.ClicksPerSec_TXT = QtWidgets.QLabel(self.centralwidget)
        self.ClicksPerSec_TXT.setGeometry(QtCore.QRect(20, 50, 91, 16))
        self.ClicksPerSec_TXT.setObjectName("ClicksPerSec_TXT")
        self.Start_BTN = QtWidgets.QPushButton(self.centralwidget)
        self.Start_BTN.setGeometry(QtCore.QRect(20, 110, 75, 23))
        self.Start_BTN.setObjectName("Start_BTN")
        self.Start_BTN.clicked.connect(lambda: start(self))
        self.Stop_BTN = QtWidgets.QPushButton(self.centralwidget)
        self.Stop_BTN.setGeometry(QtCore.QRect(120, 110, 75, 23))
        self.Stop_BTN.setObjectName("Stop_BTN")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 208, 21))
        self.menubar.setObjectName("menubar")
        self.menugay = QtWidgets.QMenu(self.menubar)
        self.menugay.setObjectName("menugay")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menugay.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "KaiKlicker"))
        self.Intro_TXT.setText(_translate("MainWindow", "Welcome to KaiKlicker 1.0! awa awa"))
        self.ClicksPerSec_TXT.setText(_translate("MainWindow", "Clcks Per Second:"))
        self.Start_BTN.setText(_translate("MainWindow", "Start (f6)"))
        self.Stop_BTN.setText(_translate("MainWindow", "Stop (f6)"))
        self.menugay.setTitle(_translate("MainWindow", "gay"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

if on:
    def run(self):
        while self.program_running:
            while self.running:
                mouse.click(self.button)
                time.sleep(self.delay)
            time.sleep(0.1)
